# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  testJob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "Release file hello world" > file.txt'
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: file.txt
          asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
